UPLOAD_1C_FOLDER_ID = 365441
ARCHIVED_FOLDER_ID = 367621
ERROR_FOLDER_ID = 374185

DISK_ENTITY_TYPE_ALIAS = 'TYPE'
DISK_FILE_DL_URL_ALIAS = 'DOWNLOAD_URL'
DISK_FILE_NAME_ALIAS = 'NAME'
DISK_FILE_ID_ALIAS = 'ID'

CONTACT_ID_ALIAS = 'ID'
CONTACT_NAME_ALIAS = 'NAME'
CONTACT_LAST_NAME_ALIAS = 'LAST_NAME'
CONTACT_PATR_ALIAS = 'SECOND_NAME'
CONTACT_PHONE_ALIAS = 'PHONE'
CONTACT_PHONE_VALUE_ALIAS = 'VALUE'
CONTACT_PHONE_TYPE_ALIAS = 'VALUE_TYPE'
CONTACT_BIRTHDAY_ALIAS = 'BIRTHDATE'
CONTACT_SEX_ALIAS = 'UF_CRM_3736286084024'
CONTACT_TYPE_ALIAS = 'TYPE_ID'
CONTACT_SOURCE_ALIAS = 'SOURCE_ID'

DEAL_WAREHOUSE_ALIAS = 'UF_CRM_1572865373376'
DEAL_SUM_ALIAS = 'OPPORTUNITY'
DEAL_1C_CODE_ALIAS = 'UF_CRM_1603309097471'
DEAL_CONTACT_IDS_ALIAS = 'CONTACT_IDS'
DEAL_DATE_ALIAS = 'UF_CRM_1572436074496'
DEAL_CATEGORY_ALIAS = 'CATEGORY_ID'
DEAL_SOURCE_ALIAS = 'SOURCE_ID'
DEAL_DELIVERY_TYPE_ALIAS = 'UF_CRM_1572419729488'

UTM_SOURCE_MARK_ALIAS = 'UTM_SOURCE'
